#pragma once

#include <string_view>

/**
 * @file TCarrierFlowDirection.hpp
 * @brief Canonical carrier-flow direction semantics for ASCC runtime evidence.
 *
 * Carrier flow directions describe how a carrier participated in the bridge
 * runtime exchange lifecycle.
 *
 * These directions are intentionally runtime-oriented rather than transport-
 * oriented. They are consumed by:
 *
 * - carrier flow runtime
 * - validation/runtime diagnostics
 * - readiness evidence
 * - facade projections
 * - protocol/session evidence reports
 * - participant exchange observation
 *
 * The goal is to provide one canonical vocabulary for carrier runtime motion
 * and lifecycle observation.
 */

namespace assembler::communication_context
{
    enum class TCarrierFlowDirection
    {
        unknown,

        // Carrier was emitted/generated by a participant/runtime side.
        produced,

        // Carrier was accepted/consumed by a participant/runtime side.
        consumed,

        // Carrier was observed without ownership transfer.
        observed,

        // Carrier was forwarded/bridged across a boundary.
        relayed,

        // Carrier processing was intentionally deferred.
        deferred,

        // Carrier was rejected by validation/admission/runtime policy.
        rejected,

        // Carrier processing failed unexpectedly.
        failed
    };

    [[nodiscard]] constexpr std::string_view to_string(
        TCarrierFlowDirection direction) noexcept
    {
        switch (direction)
        {
            case TCarrierFlowDirection::unknown:
                return "unknown";

            case TCarrierFlowDirection::produced:
                return "produced";

            case TCarrierFlowDirection::consumed:
                return "consumed";

            case TCarrierFlowDirection::observed:
                return "observed";

            case TCarrierFlowDirection::relayed:
                return "relayed";

            case TCarrierFlowDirection::deferred:
                return "deferred";

            case TCarrierFlowDirection::rejected:
                return "rejected";

            case TCarrierFlowDirection::failed:
                return "failed";
        }

        return "unknown";
    }

    [[nodiscard]] constexpr bool is_primary_exchange_direction(
        TCarrierFlowDirection direction) noexcept
    {
        return direction == TCarrierFlowDirection::produced
            || direction == TCarrierFlowDirection::consumed;
    }

    [[nodiscard]] constexpr bool is_observation_direction(
        TCarrierFlowDirection direction) noexcept
    {
        return direction == TCarrierFlowDirection::observed
            || direction == TCarrierFlowDirection::relayed;
    }

    [[nodiscard]] constexpr bool is_failure_direction(
        TCarrierFlowDirection direction) noexcept
    {
        return direction == TCarrierFlowDirection::rejected
            || direction == TCarrierFlowDirection::failed;
    }

    [[nodiscard]] constexpr bool is_non_terminal_direction(
        TCarrierFlowDirection direction) noexcept
    {
        return direction == TCarrierFlowDirection::deferred;
    }
}
